# Generated by Django 5.0.3 on 2024-05-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ritah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='intake',
            field=models.IntegerField(),
        ),
    ]
