# Generated by Django 5.0.3 on 2024-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ritah', '0002_alter_reg_intake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='sponsorhip',
            new_name='sponsorship',
        ),
        migrations.AlterField(
            model_name='reg',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
