# Generated by Django 5.0.3 on 2024-05-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ritah', '0005_alter_reg_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
