# Generated by Django 5.0.3 on 2024-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ritah', '0006_alter_reg_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='entry_scheme',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
