# Generated by Django 5.0.6 on 2024-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clarkeapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="male",
                max_length=50,
            ),
        ),
    ]
