# Generated by Django 4.2.11 on 2024-05-17 09:40

from django.db import migrations, models
import django.utils.timezone
import formApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[formApp.models.validate_letters])),
                ('last_name', models.CharField(max_length=50, validators=[formApp.models.validate_letters])),
                ('course', models.CharField(choices=[('Certificate_in_health_science', 'Certificate_in_health_science'), ('Certificate_in_applied_technology', 'Certificate_in_applied_tecnology'), ('Bachelor_in_information_technology', 'Bachelor_in_information_technology'), ('Bachelor_in_business_technology', 'Bachelor_in_business_technology'), ('Masters_in_business_health', 'Masters_in_business_health')], max_length=100, null=True)),
                ('entry_scheme', models.CharField(choices=[('A_level certificate', 'A_level certificate'), ('Adult/mature learning', 'Adult/mature learning'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=100, null=True)),
                ('intake', models.CharField(choices=[('January intake', 'January intake'), ('May intake', 'May intake'), ('August intake', 'August intake')], max_length=100, null=True)),
                ('sponsorship', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('Bursary', 'Bursary')], max_length=100, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=100)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('residence', models.CharField(max_length=255, validators=[formApp.models.validate_letters])),
            ],
        ),
    ]
