# Generated by Django 5.0.3 on 2024-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('Bachelor of bussiness', 'Bachelor of business'), ('Certificate in health science', 'Certificate in health science'), ('Master of public health', 'Master of public health')], max_length=100)),
                ('entry_scheme', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelors', 'Bachelors'), ('Adult', 'Adult')], max_length=100)),
                ('intake', models.CharField(choices=[('August intake', 'August intake'), ('May intake', 'May intake'), ('January intake', 'January intake')], max_length=100)),
                ('sponsorship', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('Bursary', 'Bursary')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('residence', models.CharField(max_length=100)),
            ],
        ),
    ]
