# Generated by Django 5.0.3 on 2024-05-17 10:24

import refactor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refactor', '0002_alter_user_course_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='YYYY-MM-DD', validators=[refactor.models.validate_date_of_birth, refactor.models.validate_age]),
        ),
    ]
