# Generated by Django 5.0.3 on 2024-05-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refactor', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='entry_scheme',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='intake',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='sponsorship',
            field=models.CharField(max_length=100),
        ),
    ]
