# Generated by Django 5.0.3 on 2024-05-17 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^.{3}$', code='nomatch', message='minimum length must be atleast 3 characters')])),
                ('last_Name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^.{3}$', code='nomatch', message='minimum length must be atleast 3 characters')])),
                ('course', models.CharField(choices=[('CHS', 'Certificate in Health Science'), ('CAT', 'Certicate in Applied Technology'), ('BIT', 'Bachelor of Information Technology'), ('BBT', 'Bachelor in Business Technology'), ('MPH', 'Bachelor of Public Health')], max_length=20)),
                ('entry_Scheme', models.CharField(choices=[('a level certificate', 'A-Level Certificate'), ('learning', 'Adult/Mature Learning'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'BachelorS')], max_length=20)),
                ('sponsorship', models.CharField(choices=[('P', 'Private'), ('G', 'Government'), ('B', 'Bursary')], max_length=20)),
                ('intake', models.CharField(choices=[('January', 'January Intake'), ('May', 'May Intake'), ('August', 'August Intake')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('date_Of_Birth', models.DateField()),
                ('residence', models.CharField(max_length=255)),
            ],
        ),
    ]
