# Generated by Django 5.0.3 on 2024-05-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='entry_Scheme',
            new_name='entry_scheme',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
