# Generated by Django 5.0.4 on 2024-05-17 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Date_Of_Birth',
            new_name='Date_of_Birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='user',
            name='Firstname',
            field=models.CharField(default='time', max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Lastname',
            field=models.CharField(default='name', max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='Course',
            field=models.CharField(choices=[('Certificate in Health Science', 'Certificate in Health Science'), ('Certificate in Applied Technology', 'Certificate in Applied Technology'), ('Bachelor of  Information Technology', 'Bachelor of Information Technology'), ('Bachelors in Business Technology', 'Bachelors in Business Technology'), ('Master of Public Health', 'Master of Public ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Entry_Scheme',
            field=models.CharField(choices=[('A_Level certificate', 'A_Level certificate'), ('Adult/Ma', ' Adult/Mature Learning'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelors', 'Bachelors')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Intake',
            field=models.CharField(choices=[('January Intake', 'January Intake'), ('May Intake', 'May Intake'), ('August Intake', 'August Intake')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Residence',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Sponsorship',
            field=models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('Bursary', 'Bursary')], max_length=255),
        ),
    ]
