# Generated by Django 5.0.4 on 2024-05-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_application',
            name='sponsorship',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
